### ISSUE TITLE
Requires a version

### ISSUE THREAD

**Issue by soljohnston777** [eddturtle/direct-upload#12]
composer require eddturtle/direct-upload

requires a version number when use composer.  

I did a git clone to get everything, but this could be an issue for people who don't use git.

**Comment by eddturtle** [comment]
Sorry, I don't quite understand, you should be able to run that command and it will pull the latest copy.

Here's what it does for mine: https://dl.dropboxusercontent.com/u/459290/github-prs/composer-issue.png

**Comment by soljohnston777** [comment]
It only worked for me with your other github direct-upload-s3-signaturev4-master. For this one it didn't work, but I think I found the problem: 

**this composer.json works from your example direct-upload-s3-signaturev4-master.:**
{
    "require": {
        "eddturtle/direct-upload": "^1.6"
    }
}



**The one from this repository looked like it was missing that require:**
{
    "name": "eddturtle/direct-upload",
    "description": "Composer Package to build an AWS Signature ready to Direct Upload to S3",
    "license": "MIT",
    "keywords": [
        "direct",
        "upload",
        "aws",
        "s3",
        "php",
        "amazon",
        "signature"
    ],
    "authors": [
        {
            "name": "Edd Turtle",
            "email": "edd@designedbyaturtle.co.uk",
            "homepage": "https://www.designedbyaturtle.co.uk"
        }
    ],
    "require": {
        "php" : "~5.5|~7.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.8"
    },
    "autoload": {
        "psr-4": {
            "EddTurtle\\DirectUpload\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Eddturtle\\DirectUpload\\Tests\\": "tests/"
        }
    }
}
