### ISSUE TITLE
I'm getting an upload error if...

### ISSUE THREAD

**Issue by JeanPierreFig** [eddturtle/direct-upload#15]
I'm getting an error upload error if I place bootstrap divs inside the form that will upload the file. Why is this?

**Comment by eddturtle** [comment]
Good question, can you show some example code to work with?

**Comment by JeanPierreFig** [comment]
```
<form action="<?php echo $upload->getFormUrl(); ?>"
method="POST"
 enctype="multipart/form-data"
class="direct-upload form-horizontal">
<?php echo $upload->getFormInputsAsHtml(); ?>

		        <div class='form-group '>
				 <div class='col-sm-10'>
					 <div class="input-group">
					 	<label class="input-group-btn">
							<span class="btn btn-primary">
							    Choose file <input type="file" name="file" id="file"  style="display: none;">
							</span>
						</label>
				            <input type="text" class="form-control validate" name="filename" readonly style="margin-top: 0px;">
				      </div>
				 </div>
			</div>
								
	       </form>
```

> I'm getting a post 403 (Forbidden)

but if it's just the form with the input field then it works?

**Comment by eddturtle** [comment]
Would you be able to try it again without the 2nd input (`<input type="text" class="form-control validate" name="filename" readonly>`)? The signature might not match if other inputs are passed

**Comment by JeanPierreFig** [comment]
That worked.

**Comment by eddturtle** [comment]
Not sure there's much I can do about this... other than maybe improve docs to mention about additional inputs.
