### ISSUE TITLE
How to ensure Key isn't getting changed?

### ISSUE THREAD

**Issue by rohitcoder** [eddturtle/direct-upload#26]
Can you suggest me a way, how can i modify this script in a way by which it checks if key is wrong.

### Use case

Every user uploads image to its own folder in our s3 bucket for example 

User 1 => 1/profile/image.png
User 2 => 2/profile/image.png

Now, i can see user can change key from inspect element of chrome, is there any workaround for this?

**Comment by rohitcoder** [comment]
You can suggest me a way, i am having good experience with customizing scripts and making stuffs, so you can suggest me any kind of workaround :)

**Comment by eddturtle** [comment]
As part of the options array you can pass a `valid_prefix`. This can only check the start of the key, but that should be perfect for you. If you're valid prefix was {{ID}}/profile/image - with a dynamic id passed in, it will limit the uploads.

**Comment by rohitcoder** [comment]
Thanks! Working as expected :)

Again thanks for making this whole process easy as a game!
