### ISSUE TITLE
S3 URL change in signature.php

### ISSUE THREAD

**Issue by andrebruton** [eddturtle/direct-upload#28]
In Line 133, you need to change the dash to a dot for the URL to work (at least for the af-south-1 endpoint

Old: 
```
        // Only the us-east-1 region is exempt from needing the region in the url.
        if ($region !== "us-east-1") {
            $middle = "-" . $region;
        } else {
            $middle = "";
        }
```

New:
```
        // Only the us-east-1 region is exempt from needing the region in the url.
        if ($region !== "us-east-1") {
            $middle = "." . $region;
        } else {
            $middle = "";
        }
```

**Comment by eddturtle** [comment]
I've made this change to the master branch (along with the new region).

Using the dash, seemed to be the old way: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#s3-dash-region so I've updated it to the dot like you mentioned and seems to work as normal.

You should be able to use it under `dev-master` now, might hold off on a release for a few days to see if I can find time to look into #21.
