### ISSUE TITLE
Unzip issue

### ISSUE THREAD

**Issue by 89z** [eddturtle/direct-upload#29]
Sorry I couldnt find the correct repo to post this. This post:

https://golangcode.com/unzip-files-in-go

has a serious issue. The code loops through the entries in the Zip file, and creates folder if item is a folder, and creates file if item is a file. Well, Zip archives arent required to list folder items at all. So if your code was run against one of these archives, it would fail, as no directories would ever be created, and the first non-root file found would crash the program.

https://stackoverflow.com/questions/65617164

**Comment by eddturtle** [comment]
(I've sent you an email in reply)
