### ISSUE TITLE
v1.5.1 broke getFormInputs

### ISSUE THREAD

**Issue by crsepulv** [eddturtle/direct-upload#9]
Hi, in composer v1.5.1 the key: ACL on getFormInputs() returns an object, previous version was a text.

This was a mistake or on purpose?

**Comment by eddturtle** [comment]
Hi, this was an issue if you were using the values directly.  It didn't come up in testing because php was casting it to a string when echo-ing and thus still working.  I've pushed some new code, I'll review it and release a .2 if it's all good.

**Comment by crsepulv** [comment]
Great. I create a backend API that send getFormInputs() as JSON.  
I'm not using the getFormInputsAsHtml().
